// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrqehgsnhadgkzbrfnhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycWVoZ3NuaGFkZ2t6YnJmbmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTgxMDEsImV4cCI6MjA2NDMzNDEwMX0._aFavsMuaGp1VcjxrgjzUAHGyCf2zOJyQDUHfj-JoWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);